spring:
  application:
    name: internal-payment
  datasource:
    url: jdbc:hsqldb:file:db/internal_payments/store
    username: sa
    password:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver

  cloud:
    consul:
      discovery:
        tags: accountNumber=9999, GATEWAY_SERVICE
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sleuth:
    sampler:
      percentage: 1.0
server:
  port: 8093

